"""Single weekly consolidated digest — sent every Sunday 06:00.

This is the ONLY recurring email the user receives. All per-area reports
are written to /mnt/usb-archive/reports/<ISO-week>/ as HTML files; this
digest summarises and links to them.
"""

from __future__ import annotations

import argparse
import sys
from datetime import date, timedelta

from ..common import db, email_send
from ..common.config import DIGEST_RECIPIENT
from ..common.logging_setup import get_logger
from . import per_area, sections

LOGGER = get_logger("reports.master_digest")


HEADER = """
<div style="background:linear-gradient(135deg,#2c3e50,#34495e);
            color:#fff;padding:24px;border-radius:8px;margin-bottom:24px;">
  <h1 style="margin:0;font-size:28px;">Workhorse Weekly Digest</h1>
  <p style="margin:8px 0 0 0;opacity:0.85;">Single consolidated report for the week ending {today}</p>
</div>
"""

SUMMARY_TEMPLATE = """
<table cellspacing="0" cellpadding="6" style="border-collapse:collapse;width:100%;
       margin-bottom:20px;font-family:Arial,sans-serif;">
  <thead>
    <tr style="background:#ecf0f1;">
      <th align="left">Area</th>
      <th align="right">New this week</th>
      <th align="left">Notes</th>
    </tr>
  </thead>
  <tbody>{rows}</tbody>
</table>
"""

FOOTER = """
<hr style="border:none;border-top:1px solid #eee;margin:24px 0;">
<p style="color:#7f8c8d;font-size:0.85em;">
  Per-area HTML reports are saved to
  <code>/mnt/usb-archive/reports/{week}/</code> on the MacBook.<br>
  Course CSV export at <code>/mnt/usb-archive/databases/courses_export.csv</code>.<br>
  Generated by Workhorse v2 on the MacBook (Ubuntu).
</p>
"""


def _summary_row(label: str, count: int, note: str) -> str:
    return (
        f'<tr style="border-bottom:1px solid #ecf0f1;">'
        f'<td><strong>{label}</strong></td>'
        f'<td align="right">{count}</td>'
        f'<td>{note}</td>'
        f'</tr>'
    )


def build_digest_html() -> tuple[str, int]:
    """Compose the consolidated HTML body. Returns (html, total_items)."""
    today = date.today().isoformat()
    iso = date.today().isocalendar()
    week = f"{iso.year}-W{iso.week:02d}"

    # Build each section once, reuse for both per-area files and digest
    s_courses = sections.courses_section(limit=15)
    s_trends = sections.job_trends_section(limit=10)
    s_financial = sections.financial_section(limit=4)
    s_funding = sections.funding_section(limit=15)
    s_jobs = sections.jobs_section(limit=15)
    s_film = sections.film_section(limit=15)
    s_coursepulse = sections.coursepulse_section(limit=20)
    s_research = sections.research_section(limit=15)
    s_procurement = sections.procurement_section(limit=15)
    s_education = sections.education_resources_section(limit=15)
    s_sen = sections.sen_section(limit=12)
    s_shakespeare = sections.shakespeare_section(limit=12)
    s_finance = sections.finance_bulletins_section(limit=12)
    s_gmail = sections.gmail_section(limit=15)

    # Write per-area HTML files to USB (reuses already-fetched sections)
    per_area.generate_all()

    summary = SUMMARY_TEMPLATE.format(
        rows="".join([
            _summary_row("Courses (MyCourseMatchmaker)", s_courses["count"], "indexed this week"),
            _summary_row("CoursePulse (Curriculum Intel)", s_coursepulse["count"], "pathways + insights"),
            _summary_row("Procurement (FHE + builds)", s_procurement["count"], "tenders + frameworks"),
            _summary_row("Education Resources (Maieus)", s_education["count"], "exam-board + platforms"),
            _summary_row("SEN & Excluded Learners", s_sen["count"], "policy + inclusion tools"),
            _summary_row("Shakespeare Engagement", s_shakespeare["count"], "modern media + practical"),
            _summary_row("Finance Bulletins", s_finance["count"], "HMRC/FCA/BoE/DfE/ONS"),
            _summary_row("Job trends", s_trends["count"], "skill / occupation signals"),
            _summary_row("Financial research", s_financial["count"], "Perplexity topics refreshed"),
            _summary_row("Funding & grants", s_funding["count"], "open opportunities"),
            _summary_row("Jobs (EdTech / HE)", s_jobs["count"], "live listings"),
            _summary_row("Film & script", s_film["count"], "open opportunities"),
            _summary_row("AI Research (Perplexity + Gemini)", s_research["count"], "dual-engine queries"),
            _summary_row("Inbox (Gmail)", s_gmail["count"], "relevant emails"),
        ])
    )

    body = HEADER.format(today=today) + summary
    body += s_procurement["html"]
    body += s_coursepulse["html"]
    body += s_education["html"]
    body += s_sen["html"]
    body += s_shakespeare["html"]
    body += s_funding["html"]
    body += s_jobs["html"]
    body += s_film["html"]
    body += s_courses["html"]
    body += s_finance["html"]
    body += s_trends["html"]
    body += s_financial["html"]
    body += s_research["html"]
    body += s_gmail["html"]
    body += FOOTER.format(week=week)

    total = sum(s["count"] for s in [
        s_courses, s_coursepulse, s_procurement, s_education, s_sen,
        s_shakespeare, s_finance, s_trends, s_financial, s_funding,
        s_jobs, s_film, s_research, s_gmail
    ])
    return body, total


def _log(total: int) -> None:
    today = date.today()
    monday = today - timedelta(days=today.weekday())
    sunday = monday + timedelta(days=6)
    db.execute(
        """
        INSERT INTO weekly_digests (
          digest_area, week_start, week_end, item_count, email_sent_at, recipient
        ) VALUES ('master', %s, %s, %s, NOW(), %s)
        ON CONFLICT (digest_area, week_start) DO UPDATE
          SET item_count = EXCLUDED.item_count,
              email_sent_at = EXCLUDED.email_sent_at,
              recipient = EXCLUDED.recipient
        """,
        (monday, sunday, total, DIGEST_RECIPIENT),
    )


def run(dry_run: bool = False, days: int = 7) -> None:
    sections.set_lookback_days(days)
    label = "Weekly Digest" if days >= 7 else f"{days}-day Update"
    LOGGER.info("Building master digest (lookback=%d days)...", days)
    html, total = build_digest_html()
    today = date.today().isoformat()
    subject = f"Workhorse {label} — {today} ({total} items)"
    if dry_run:
        print(subject)
        print(html[:2000])
        print("... (truncated)")
        return
    email_send.send_html(subject, html)
    if days >= 7:
        _log(total)
    LOGGER.info("Master digest sent: %s (%d items)", subject, total)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--days", type=int, default=7,
                        help="Lookback window in days (7 for Sunday, 3 for Mon/Wed)")
    args = parser.parse_args()
    try:
        run(dry_run=args.dry_run, days=args.days)
    except Exception as exc:  # noqa: BLE001
        LOGGER.exception("Master digest failed: %s", exc)
        sys.exit(1)
